package main

import (
  "log"
  "runtime"
)
/*  The Version function of runtime reutrns the runtime/internal/sys
    cat $GOROOT/src/runtime/internal/sys/zversion.go

    Dot Go file generated by $go dist tool
    version is resolved by the findgoversion function under
    go/src/cmd/dist/build.go

    $GOROOT/VERSION.cache first used if existed else created
*/

func main() {
  log.Printf(info, "Example", runtime.Version())
}

const info = `
  Application %s Starting.
  The Binary Was Build By Go: %s`
